import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, "..", "..");
const outputDir = join(scriptDir, "output");
const outputPath = join(outputDir, "codex_handoff.md");

function readHarnessFile(fileName) {
  return readFileSync(join(scriptDir, fileName), "utf8").trim();
}

function stripTopLevelHeading(markdown) {
  return markdown.replace(/^# .+\r?\n+/, "").trim();
}

function runGit(args) {
  try {
    const value = execFileSync("git", args, {
      cwd: repoRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"]
    }).trim();

    return value || "unknown";
  } catch {
    return "unknown";
  }
}

function escapeTableCell(value) {
  return String(value).replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function qaMatrixSummary(matrix) {
  const rows = matrix.categories.map((category) => {
    const evidence = category.evidence.join(", ");
    return `| ${escapeTableCell(category.name)} | ${escapeTableCell(category.risk)} | ${category.checks.length} | ${escapeTableCell(evidence)} |`;
  });

  return [
    `Matrix version: ${matrix.version}`,
    "",
    "| Category | Risk | Checks | Evidence |",
    "| --- | --- | ---: | --- |",
    ...rows
  ].join("\n");
}

const now = new Date();
const localDateTime = new Intl.DateTimeFormat(undefined, {
  dateStyle: "full",
  timeStyle: "long"
}).format(now);

const branch = runGit(["rev-parse", "--abbrev-ref", "HEAD"]);
const commit = runGit(["rev-parse", "HEAD"]);
const shortCommit = runGit(["rev-parse", "--short", "HEAD"]);
const knownRegressions = stripTopLevelHeading(readHarnessFile("known-regressions.md"));
const latestFindings = stripTopLevelHeading(readHarnessFile("latest-findings.md"));
const qaMatrix = JSON.parse(readHarnessFile("qa-matrix.json"));

const handoff = `# Seat Planner Codex Handoff

Generated by \`npm run qa:handoff\`.

## Current Date/Time

- Local: ${localDateTime}
- ISO: ${now.toISOString()}

## Git State

- Branch: \`${branch}\`
- Commit: \`${shortCommit}\` (${commit})

## Seat Planner Project Context

Seat Planner is a private office seat-planning app built with Next.js App Router, React,
TypeScript, Tailwind CSS, Supabase Auth, Supabase Postgres, RLS, and Next.js server actions.
Authenticated viewers see the published seating map at \`/\`. Admins edit a draft map at
\`/admin\`, manage data at \`/admin/management\`, and publish draft changes when ready.

## Non-Negotiable Safety Rules

- Do not change production Seat Planner behavior from this harness.
- Do not change Supabase schema.
- Do not change auth.
- Do not change viewer/admin routing.
- Do not add OpenAI API keys or environment variables.
- Do not add runtime dependencies to the app.
- Do not add client-side AI features.
- Keep this system entirely repo-side and tooling-side.
- Keep draft and published seat behavior separate.
- Treat Supabase RLS, \`profiles.role\`, and server-side checks as the security boundary.
- Never print, expose, commit, or transmit secrets.

## Known Regressions

${knownRegressions}

## QA Matrix Summary

${qaMatrixSummary(qaMatrix)}

## Latest Findings

${latestFindings}

## Suggested Next Pass Format

Use this structure for the next Codex pass:

1. Objective: one sentence naming the requested change or QA target.
2. Safety boundary: confirm production behavior, auth, routing, schema, and secrets are untouched unless explicitly in scope.
3. Files changed: list only files changed in the pass.
4. Evidence: include command results and manual QA notes, especially viewer/admin route checks.
5. Regression review: mention any known-regression items checked or still unverified.
6. Remaining risk: call out gaps plainly.

## Commands To Run

\`\`\`bash
npm test
npm run typecheck
npm run lint
npm run build
\`\`\`
`;

mkdirSync(outputDir, { recursive: true });
writeFileSync(outputPath, `${handoff.trim()}\n`, "utf8");

console.log(`Wrote ${outputPath}`);
